baseURL = "https://www.yamler.io"
title = "YAMLer 文摘"
copyright = ""
paginate = 3
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "dustise"
  description = "每天推荐前一天的六篇文章，多数是云原生，偶尔夹带私货。"
  #   homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "dustise@gmail.com"
    # facebook = "https://facebook.com"
    twitter = "https://twitter.com/dustise"
    # linkedin = "https://linkedin.com"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    github = "https://github.com/fleeto"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
